services:
  eddash:
    build: .
    container_name: eddash
    ports:
      - "0310:0310"
    environment:
      - DASHBOARD_TITLE=${DASHBOARD_TITLE:-Server Dashboard}
      - FALLBACK_TAILSCALE_IP=${FALLBACK_TAILSCALE_IP:-100.83.252.53}
    volumes:
      - /proc:/proc:ro
      - /var/lib/apt/lists:/var/lib/apt/lists:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev:/dev:ro
      - /run/systemd/system:/run/systemd/system:ro
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN